name: Test

on:
  push:

jobs:
  issue:
    name: Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Install correct maven version
        run: |
          mvn -v
          mvn wrapper:wrapper -Dmaven=3.9.1
          ./mvnw -v
      - run: ./mvnw compile
      - run: bash shell.sh

  workaround:
    name: Potential Workaround
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Install correct maven version
        run: |
          mvn -v
          mvn wrapper:wrapper -Dmaven=3.9.1
          ./mvnw -v
      - run: bash fix.sh
      - run: ./mvnw compile
      - run: bash shell.sh
